name: PR Build and Test

# Kích hoạt khi có Pull Request được mở hoặc cập nhật
on:
  pull_request:
    branches:
      - main # Kiểm tra khi có PR vào nhánh chính, bạn có thể thay đổi sang nhánh khác nếu cần

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Thiết lập môi trường Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: yarn

      - name: Enable Corepack
        run: corepack enable

      # Cài đặt dependencies bằng Yarn để đồng bộ với dự án
      - name: Install dependencies
        run: yarn install --immutable

      # Build dự án
      - name: Build
        run: yarn build

      # Chạy các test (ở chế độ non-watch cho môi trường CI)
      - name: Run tests
        run: yarn test --run
